version: '3.6'

networks:
  nginx-proxy:
    external: true
  default:
    external:
      name: flask_network

services:
  flask_webapp:
    build:
      context: .
    container_name: flask_webapp
    ports:
    - "9000:9000"
    restart: 'always'

    networks:
      default:
        ipv4_address: 100.100.0.10
      nginx-proxy: null

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
